language: node_js
node_js:
- "8"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
install:
  - npm install
script:
  - $(npm bin)/start-server-and-test dev http-get://localhost:8081 cy-test
